### ISSUE TITLE
add feature raspberry pico with adxl345 support

### ISSUE THREAD

**Issue by kyon03** [th33xitus/kiauh#114]
https://www.reddit.com/r/klippers/comments/owqvo2/raspberry_pi_pico_as_a_secondary_mcu_for/

we can use cheap andriod box as klipper then we can ad this module as reasonance testing/calibrator :D

**Comment by th33xitus** [comment]
Im currently ocassionally following some discussions on the Klipper discord where you take part in i guess and it seems that it isn't as easy as it sounds to compile the firmware on a pi? So i think i will freeze/close this FR until we know more. It's a small problem anyways because i don't own a pico. A few month ago i bought a blue pill for adxl tuning... so i don't think that i will buy a pico anytime soon too. 😄
