### ISSUE TITLE
Webcamd uses vcgencmd, it would be useful to find out if the script is running on the platform where it is available before using it

### ISSUE THREAD

**Issue by wykys** [th33xitus/kiauh#140]

**Comment by th33xitus** [comment]
I don't understand. Please elaborate on this issue.

**Comment by wykys** [comment]
For example, this command is not available on orangepi ...

**Comment by th33xitus** [comment]
And what is it needed for?
Im not the maintainer of the webcamd script or the mjpg-streamer repository.

**Comment by wykys** [comment]
I thought you were the author of the `webcamd` script...

I didn't look into the installation code. Only now have we glanced at you downloading the script: https://github.com/th33xitus/kiauh/blob/master/scripts/install_mjpg-streamer.sh#L51
from:
https://github.com/mainsail-crew/MainsailOS/blob/master/src/modules/mjpgstreamer/filesystem/root/usr/local/bin/webcamd

The problem is with the `webcamd` script just mentioned, so the problem probably belongs there.

**Comment by th33xitus** [comment]
No that script was created by someone else.
I am not sure if someone will fix it... currently there is some development happening on a project which utilizes for example ustreamer instead of mjpg-streamer. Maybe this works even better for you? This is the project: https://github.com/mainsail-crew/crowsnest

**Comment by wykys** [comment]
I'll try, I also ran mjpg-streamer, but I had to edit the webcamd ...
