### ISSUE TITLE
Moonraker cannot be Installed with SKR Brand Klipper

### ISSUE THREAD

**Issue by Heisenberg19x** [th33xitus/kiauh#154]
### What happened

![grafik](https://user-images.githubusercontent.com/92603513/146461692-1d92e3fd-fa16-4374-8ed8-330a720d9f6d.png)
Klipper is installed at the shown SKR Brand for the BTT SKR Mini E3 V3

### What did you expect to happen

![grafik](https://user-images.githubusercontent.com/92603513/146461790-1ea869e8-44ce-4434-99a3-bfa6832b5686.png)
When trying to Install Moonraker KIAUH says no Klipper Installed

![grafik](https://user-images.githubusercontent.com/92603513/146461871-b9e90a7e-850b-4248-ae2b-64ff515c36f0.png)
When trying to Install Klipper KIAUH says Klipper already Installed

### How to reproduce

Install SKR Brand Klipper and try

**Comment by StefanMeGit** [comment]
The same happens to me... running KLIPPER on an Ardunie DUE. It looks like its not an SKR Brand Klipper problem. I am using the master branch.

![image](https://user-images.githubusercontent.com/16327026/146645725-8f8f8088-4c77-4ec9-9784-f70e1277aaf1.png)

**Comment by th33xitus** [comment]
The brand is not really the problem here.
The issue is, that you both probably have a rather old Klipper installation which means Klipper is installed as an init.d service.
A while ago i changed KIAUH the way that it specifically only looks for systemd service files anymore. And throws that error if none are found. Using the official upstream in that case is no real issue, because one could easily just re-install Klipper with KIAUH and then the service type is the expected one. But installations of a forked/modified Klipper would break because currently KIAUH only installs the official upstream Klipper... no inofficial custom forks.

Im currently thinking about a solution and if it still would be okay to just allow the installation of Moonraker no matter which type of Klipper service exists (technically Moonraker doesn't even need a Klipper service available). In theory i could decouple the Moonraker setup completely from any existing Klipper installation. This would, on the other hand, get rid of some "comfort" as in pre-entering the correct number of needed Moonraker instaces if more than one Klipper instances are found. But at that point i probably should ask myself if limiting installations is worth such little comfort gains in exchange. Probably not.

I try to come up with a solution.

**Comment by th33xitus** [comment]
Commit https://github.com/th33xitus/kiauh/commit/4d834db5df781adbb8019b6349730eab22750f37 now "unlinks" the Moonraker installation part of the script completely from Klipper. You are not limited anymore if there is no Klipper installation at all or a very old one (those older init.d services). The only thing that is left is a little part which counts any exisitng Klipper installations (no matter if systemd or init.d) for displaying it to the user simply for informational reasons.
