### ISSUE TITLE
Install / Configure Klipperscreen with RDP access to use with old phones and tablets with WLAN

### ISSUE THREAD

**Issue by govido** [th33xitus/kiauh#166]
### Is your feature request related to a problem? Please describe

Klipperscreen needs a hardware screen or hacky VNC remoting solutions that you need to combine with console apps and usb debugging android phones.
The RDP solution from Devil in the klipper discourse gets rid of many problems:
https://klipper.discourse.group/t/how-to-klipperscreen-and-rdp-for-ios-android-pc-mac/1717

You can run ANY device with a LAN/WLAN connection that has some sort of RDP client on it. (your old iPhones and iPads included)
No need for VNC session redirecting or usb debugging and screen server apps.

### Describe the solution you'd like

Create an installer script that does essentially this:

sudo apt install xrdp
nano /home/pi/.xsession

Paste this 2 lines:
cd /home/pi/KlipperScreen 
exec /home/pi/.KlipperScreen-env/bin/python /home/pi/KlipperScreen/screen.py
ctrl+x

Create a new KlipperScreen.conf from Mainsail UI (where your printer.conf is) paste and save:
[main]
service = xrdp

Reboot the pi and connect with your username and password in your RDP app of choice.

**Comment by th33xitus** [comment]
Hi, thanks for the suggestion.

I don't think this feature fits the scope of KIAUH. Im not really a fan of writing any scripts which modify the sourcecode of another application. KIAUH is intended to be an installation helper tool for installing the typical base components of the Klipper "ecosystem". It is not meant to become a collection of various hacks and tweaks to make special usecases work and so i won't add features which lead into that direction. Im sorry.

Apart from that, i don't have the time and capabilities of testing all of that. Each feature i include is usually tested by myself to make sure it works the way its intended to work (i made an excuse for the KlipperScreen installer because i don't have the hardware for testing it and because it was provided by the KlipperSceen developer himself). This takes quite some time. So, with the guide you linked, i don't see a point of automating those few steps and i rather expect every user who want to achive whats written in the guide to be capable of going through that guide step by step.
