### ISSUE TITLE
Unable to install klipper, Mainsail ect...

### ISSUE THREAD

**Issue by Z3ytrox** [th33xitus/kiauh#183]
### Linux Distribution

KIAUH installation process

### What happened

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)'))': /simple/tornado/ error was given when installing ###### Installing python virtual environment... part of installation.

### What did you expect to happen

normal install

### How to reproduce

Just install KIAUH?

**Comment by th33xitus** [comment]
> Linux Distribution
KIAUH installation process

This is not a Linux Distribution.

> How to reproduce
Just install KIAUH?

This instruction seems rather unreasonable

>What happened
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)'))': /simple/tornado/ error was given when installing ###### Installing python virtual environment... part of installation.

This reads rather as an issue during the install of the python wheels and as kind of a network error while the setup tried to download the required files.


The form is intended to be filled out conscientiously in order to provide basic information at the beginning so that problems can be analyzed and (hopefully) solved more quickly. In the future, I will reserve the right to close issues whose forms have been inadequately filled out.
