### ISSUE TITLE
Updating Klipper installs python2-dev package even if python3 is used

### ISSUE THREAD

**Issue by orjanekeberg** [th33xitus/kiauh#211]
### Linux Distribution

RaspianOS (bullseye). Same behavior also on a Debian:testing system.

### What happened

When choosing to update Klipper to latest version in kiauh.sh, several packages for python2 are installed even on a system using python3 for Klipper. The python2-packages are not needed and can be manually uninstalled without any notable side effects.

### What did you expect to happen

When python3 is used, then only the python3 packages should be loaded if needed.

### How to reproduce

Use kiauh to install Klipper with the python3 option.
Go to update menu and choose to update Klipper.

### Additional information

The root cause for this may not be within kiauh but in how klipper updates are processed. I also experienced this when updating klipper from the Mainsail web interface.

**Comment by supermaker1** [comment]
I used s905L TVBox (数码视讯Q7)to install klipper with Kiauh. However, the new version of armbian firmware has some problems, so that the WiFi network card cannot work properly. I can only use the old version of firmware（Armbian_5.99_Aml-g12_Ubuntu_bionic_default_5.3.0_rtl8189ftv). The version is old, I can't install klipper using kiauh normally. The reason is that some packages cannot find the installation source，such as “python2-dev” “python3-libgpiod” “libglib2.0-bin” and so on. 
Before that, I successfully installed kilpper using kiauh under ubuntu version 20.04. So, I cppy the "sources.list" file from the ubuntu 20.04 to "Armbian_5.99_Aml-g12_Ubuntu_bionic_default_5.3.0_rtl8189ftv". Then , I run the command 
`sudo apt update`
Then, I successfully installed klipper using this file "source.list" ：D
`deb http://mirrors.aliyun.com/ubuntu-ports/ focal main restricted
deb http://mirrors.aliyun.com/ubuntu-ports/ focal-updates main restricted
deb http://mirrors.aliyun.com/ubuntu-ports/ focal universe
deb http://mirrors.aliyun.com/ubuntu-ports/ focal-updates universe
deb http://mirrors.aliyun.com/ubuntu-ports/ focal multiverse
deb http://mirrors.aliyun.com/ubuntu-ports/ focal-updates multiverse
deb http://mirrors.aliyun.com/ubuntu-ports/ focal-backports main restricted universe multiverse
deb http://mirrors.aliyun.com/ubuntu-ports/ focal-security main restricted
deb http://mirrors.aliyun.com/ubuntu-ports/ focal-security universe
deb http://mirrors.aliyun.com/ubuntu-ports/ focal-security multiverse`
if you want wo use the source,you can save zhe code to a file,and rename to "sources.list"
By zhe way，I'm from China.
