### ISSUE TITLE
Common config directory for klipper config

### ISSUE THREAD

**Issue by leptun** [th33xitus/kiauh#235]
### Is your feature request related to a problem? Please describe

I'm using kiauh with 4 very similar printers. Most of the config is identical (besides the printer specific stuff such as the serial port and Z probe offset) and every change I make I need to apply to all 4 config files manually.

### Describe the solution you'd like

It would be nice if there was an option to have a common config directory and [include] these klipper config files on a per need basis from each printer instance. This way, only one config file needs to be changed for all printers.

### Describe alternatives you've considered

I've tried doing this manually but I haven't got to a satisfactory solution. So far, I'm creating a "common" directory next to "printer-<1-4>" and in the printer.cfg I'm using a `[include ../common/UI.cfg]` directive. This works for klipper, but I can't edit this file from the web UI anymore (Mainsail). I tried creating a symlink of "common" to "printer-1/common" but moonraker just ignores it.

**Comment by th33xitus** [comment]
You can create a symlink of the printer.cfg of printer_1 for printer 2-4. You won't be able to edit the symlinked printer.cfg anymore from instances 2-4. Only instance 1 will allow you to edit the file since it has the real cfg file. But you can probably include another file acting as a new printer.cfg which is available in every printers cfg folder and given the exact same name.

So everything that is similar between all 4 printers and is not required to get changed frequently goes into printer.cfg. Everything printer specific goes into the included file.

One downside though:
SAVE_CONFIG will very likely not work on instances 2-4 and only on instance 1. Where you should not use it as it would "broadcast" to all the other printers.
