### ISSUE TITLE
Please add my theme 'Elegance' to the installer

### ISSUE THREAD

**Issue by Turbine1991** [th33xitus/kiauh#262]
### Is your feature request related to a problem? Please describe

Github:
https://github.com/Turbine1991/mainsail-theme-elegance

Thank you.

### Describe the solution you'd like

N/A

**Comment by lixxbox** [comment]
Hi @Turbine1991, 

the Mainsail themes shown in Kiauh are not managed by Kiauh itself, but in the docs repo of the Mainsail crew:
https://docs.mainsail.xyz/features/theming/themes

Kiauh only shows the list of themes and lets you install them.

Unfortunately, there are currently no written guidelines for adding community themes.
Your repo looks pretty good so far. I would just like to ask you to put a "screenshot.jpg" (spelling is key) in the root directory of the repo, which file size does not exceed 200kb and only shows Mainsail, without browser frames or other windows. 
This is important so that a preview image is shown in the docs.

After that, I'll be happy to add your theme. 🙂
