### ISSUE TITLE
Cannot Use Obico

### ISSUE THREAD

**Issue by samin50** [th33xitus/kiauh#270]
### Linux Distribution

Raspberry Pi

### What happened

After uninstalling Obico on the Pi, reinstalling it does not give me the option to reenter the 6-digit verification code. Once it is set, it doesn't seem possible to change it through KIAUH, which means I cannot use Obico. What is the workaround for this?

### What did you expect to happen

I expected that there would still be an option to set the verification code for Obico post-installation, but it is not there.

### How to reproduce

Setup Obico normally, uninstall and then reinstall. There is no option to change the code and so you cannot us Obico after you have uninstalled it before.

**Comment by th33xitus** [comment]
Upon first installation and linking of your printers, an auth-token is added to all your moonraker-obico.cfg files. If that auth token exists, the linking option is not available because KIAUH thinks its already linked (because that auth token is present in the config).
The easiest workaround would be, to delete the `auth_token = <your token>` line, save the config, restart KIAUH and then your Obico Status should already be shown as "Not linked". You can then go into the install menu and select the option to link Obico.
