### ISSUE TITLE
Time gcode_shell_command to the surrounding gcodes

### ISSUE THREAD

**Issue by m-sundman** [th33xitus/kiauh#288]
### Is your feature request related to a problem? Please describe

Now the `gcode_shell_command` executed way, way before commands that come before it in the gcode file are processed by the mcu. It seems like the shell command is executed after the preceding gcode is sent to the mcu’s input queue, rather than when that gcode is (expected to be) actually processed on the mcu.

### Describe the solution you'd like

Have the shell command execute when that gcode is (expected to be) actually processed on the mcu.

### Describe alternatives you've considered

I've tried to add a delay to the beginning of the shell command, but the time offset is too unpredictable to be anywhere near where (or rather when) it's supposed to be.

**Comment by m-sundman** [comment]
@th33xitus if gcode_shell_command isn't kiauh (which is where I got it from), then any idea in which project this feature request should be?

**Comment by th33xitus** [comment]
@m-sundman I think your issue is rather related to how Klipper evaluates and calls macros, and i think shell command macros are included in that regard. Unless i don't understand your question. In that case i would need to see an issue, but then again its probably also an even better idea to try and get help on the Klipper Discord.
