### ISSUE TITLE
G-Code Shell Command Extension not work without connection to MCU

### ISSUE THREAD

**Issue by tayanov** [th33xitus/kiauh#58]
Hi. Im use sonoff for control power of PSU my printer.
To turnoff and turnon printer im try use G-Code Shell Command Extension.

[gcode_shell_command TURN_ON]
command: curl -X POST http://sonoff_pow.local/switch/sonoff_pow_switch/turn_on
timeout: 2.
verbose: True

[gcode_shell_command TURN_OFF]
command: curl -X POST http://sonoff_pow.local/switch/sonoff_pow_switch/turn_off
timeout: 2.
verbose: True

TURN_OFF command work perfectly. But TURN_ON not, becaurse klipper not connected to MCU.

What i can to do?

Error message:
{'message': 'Lost communication with MCU \'mcu\'\nOnce the underlying issue is corrected, use the\n"FIRMWARE_RESTART" command to reset the firmware, reload the\nconfig, and restart the host software.\nPrinter is shutdown\n', 'error': 'WebRequestError'}

**Comment by th33xitus** [comment]
> TURN_OFF command work perfectly. But TURN_ON not, becaurse klipper not connected to MCU.

That makes sense.

> What i can to do?

If you use an Interface like Mainsail or Fluidd, there they have a Power Plugin where you can control the powering of your printer.
I can't say more to that because i don't use that feature, so i guess you have to have a look yourself.
https://github.com/Arksine/moonraker/blob/master/docs/configuration.md#power
